### PR TITLE
many changes (kfftools sort, kfftools shuffle)

### PR DESCRIPTION
**Pull request by rchikhi**

### CODE REVIEW

**Comment by rchikhi** [comment]
major:
* `kfftools sort`
* `kfftools shuffle`

minor:
* added .kff suffix in instr output prefix,
* input validation
* a small example

**Comment by yoann-dufresne** [comment]
@rchikhi :
I'm not sure about the addition of .kff at the end of the file names.
The unix way is that the user enters the full filename on command line.
Maybe only when there is no extension specified ?

**Comment by natir** [comment]
I have more or less the same opinion as @yoann-dufresne if the user has not put an extension it's because he doesn't want it, adding an extension automatically could go against the will of the user

**Comment by rchikhi** [comment]
fine with me but it was in accordance with how the cmdline instructions were:

`CLI::Option * output_option = subapp->add_option("-o, --outprefix", output_filename, "The kff output file prefix. For a single file the name will be <prefix>.kff, otherwise, one file per minimizer is created (<prefix>_<minimizer>.kff).");
`

it was called a "prefix", but the code didn't add ".kff" at the end as stated.

**Comment by yoann-dufresne** [comment]
You are right. It is changed on dev since a few days

**Pull request merged**
